; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name prover)
 (public_name stelf.prover)
 (modules
  State
  Psearch
  Data
  Fill
  Split
  Fixedpoint
  Introduce
  Elim
  Interactive
  Pweaken
  Prover_
  DATA
  ELIM
  FILL
  FIXEDPOINT
  INTERACTIVE
  INTRODUCE
  PSEARCH
  PWEAKEN
  SPLIT
  STATE)
 (libraries
  display
  tomega_lib
  intsyn
  global
  names
  print
  index
  modes
  typecheck
  table
  subordinate
  solvers
  opsem
  trail
  compile
  worldcheck
  formatter
  timing
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
