; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name unique)
 (public_name stelf.unique)
 (modules Unique_ UNIQUE)
 (libraries
  display
  global
  intsyn
  names
  paths
  table
  formatter
  print
  subordinate
  modes
  typecheck
  index
  solvers
  worldcheck
  timing
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
