; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name opsem)
 (public_name stelf.opsem)
 (modules
  TableParam
  AbstractTabled
  MemoTable
  SubtreeInst
  SwSubtree
  TabledMachine
  Absmachine
  AbsmachineSbt
  Ptrecon
  Trace
  Tmachine
  Swmachine
  Opsem_
  ABSMACHINE
  ABSMACHINESBT
  ABSTRACTTABLED
  MEMOTABLE
  PTRECON
  SWSUBTREE
  TABLEPARAM
  TABLEDMACHINE
  TRACE)
 (libraries
  display
  global
  table
  intsyn
  names
  print
  formatter
  index
  typecheck
  solvers
  subordinate
  tabling
  compile
  basis)
 (flags
  (:standard -w -A+5))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
