; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name tomega_lib)
 (public_name stelf.tomega)
 (modules
  Opsem
  Converter
  TomegaTypecheck
  Tomegaprint
  Tomeganames
  TomegaUnify
  Normalize
  Coverage
  Redundant
  TomegaAbstract
  Tomega_
  CONVERTER
  COVERAGE
  NORMALIZE
  OPSEM
  REDUNDANT
  TOMEGAABSTRACT
  TOMEGATYPECHECK
  TOMEGAUNIFY
  TOMEGANAMES
  TOMEGAPRINT)
 (libraries
  display
  global
  intsyn
  worldcheck
  cover
  formatter
  names
  print
  typecheck
  subordinate
  meta
  modes
  trail
  basis)
 (flags
  (:standard -w -A+5))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
