; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name flit)
 (public_name stelf.flit)
 (modules FlitOldSmlnjPack Flit_ FLIT)
 (libraries display global table intsyn names index paths print basis)
 (flags
  (:standard -w -A+5))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
