; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name subordinate)
 (public_name stelf.subordinate)
 (modules Intset Subordinate_ INTSET SUBORDINATE)
 (libraries display global table intsyn names basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
