; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name modes)
 (public_name stelf.modes)
 (modules
  Modesyn
  Modetable
  Modedec
  Modecheck
  Modeprint
  Modes_
  MODECHECK
  MODEDEC
  MODEPRINT
  MODESYN
  MODETABLE)
 (libraries
  display
  global
  table
  intsyn
  formatter
  print
  names
  paths
  index
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
