; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name style)
 (public_name stelf.style)
 (modules Style_ STYLE)
 (libraries
  display
  global
  table
  intsyn
  formatter
  print
  names
  paths
  index
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
