; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name worldcheck)
 (public_name stelf.worldcheck)
 (modules WorldSyn Worldify Worldcheck_ WORLDSYN WORLDIFY)
 (libraries
  display
  global
  timing
  table
  intsyn
  names
  paths
  formatter
  print
  index
  subordinate
  meta
  solvers
  basis)
 (flags
  (:standard -w -A+5))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
