; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name m2)
 (public_name stelf.m2)
 (modules
  MetaGlobal
  Skolem
  Metasyn
  MetaAbstract
  MetaPrint
  Init
  Search
  Lemma
  Splitting
  Filling
  Qed
  Recursion
  Strategy
  Prover
  Mpi
  M2_
  FILLING
  INIT
  LEMMA
  METAABSTRACT
  METAGLOBAL
  METAPRINT
  METASYN
  MPI
  PROVER
  QED
  RECURSION
  SEARCH
  SKOLEM
  SPLITTING
  STRATEGY)
 (libraries
  display
  stream
  global
  intsyn
  names
  modes
  paths
  formatter
  print
  typecheck
  terminate
  index
  thm
  opsem
  compile
  subordinate
  table
  timing
  debug
  solvers
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
