; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name cover)
 (public_name stelf.cover)
 (modules Total Cover_ COVER TOTAL)
 (libraries
  display
  global
  intsyn
  names
  paths
  table
  formatter
  print
  subordinate
  modes
  thm
  terminate
  index
  solvers
  worldcheck
  typecheck
  timing
  unique
  basis)
 (flags
  (:standard -w -A+5+66))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show)))
