ID
    = ?identifier?
    ;

NUM
    = ID
    ;

(* This is overly broad but never ambiguous *)
OUTER
    = ?non-commands?
    ;

STRING
    = ?balanced string literal? (* string literals lex specially, `%` followed by at least 1 `[`, and lasting till `%` followed by that same number of `]` *)
    ;

value
    = ID
    | NUM
    | STRING
    ;

mode
    = "%in"
    | "%out"
    | "%out1"
    | "%star"
    ;

(* Names suitable as rvalues *)
name
    = ID
    | "%val" , ID
    | "%(" , { ID } , ")"
    | "%val" , "(" , { ID } , ")"
    | "_"
    ;

(* Names suitable as lvalues *)
var
    = ID
    | "_"
    ;

expr1
    = 
    | value
    | STRING
    | "(" , expr , ")"
    | "%the" , expr1 , expr1
    ;

expr_trail
    = 
    | expr1
    | "%the" , expr1 , expr_trail
    | "[" , decl , "]" , expr
    | "{" , decl , "}" , expr
    | "%<-" , expr1 , expr (* Left associative *)
    | "%->" , expr1 , expr (* Right associative *)
    | "{" , mode , decl , "}" , expr (* Only in mode declerations *)
    | "{{" , ID , { ID } , "}}" , expr
    ;

expr
    = "%the" , expr1 , expr
    | expr_trail
    | expr1 , { expr1 } , [ expr_trail ]
    ;

decl
    = var , [ expr ]
    | "(" , var , { var } , ")" , [ expr ]
    ;

sort_param = 
    expr1 
    | "{", decl , "}"
    ;
command
    = "%begin" , { command } , "%end"
    | "%{" , { command } , "%}" (* Equivalent *)
    | "%term", decl 
    | "%sort", var, { sort_param }
    | "%." 
    | "%help", [value]
    | "%set", ID, value
    | "%get", ID 
    | "%quit" 
    ;

block
    = { OUTER
    | command }
    ;

file
    = { block }
    ;