include Compile
include Compress
include Cover
include Domains
include Flit
include Formatter
include Frontend
include Global
include Heuristic
include Index
include Int_inf

(* include Inverse *)
include Lambda
include M2
include Meta
include Modes
include Modules
include Msg
include Names
include Netserver
include Opsem
include Order
include Paths
include Print
include Prover
include Server
include Solvers
include Stream
include Style
include Subordinate
include Table
include Tabling
include Terminate
include Thm
include Timing
include Tomega
include Trail
include Typecheck
include Unique
include Worldcheck
