open! Basis

let integration_cases =
  [
    Case_examples_failure.test_case;
    Case_examples_ccc.test_case;
    Case_examples_church_rosser.test_case;
    Case_examples_compile_cls.test_case;
    Case_examples_compile_cpm.test_case;
    Case_examples_compile_cps.test_case;
    Case_examples_compile_cxm.test_case;
    Case_examples_compile_debruijn.test_case;
    Case_examples_compile_debruijn1.test_case;
    Case_examples_cpsocc.test_case;
    Case_examples_cut_elim.test_case;
    Case_examples_fol.test_case;
    Case_examples_guide.test_case;
    Case_examples_handbook.test_case;
    Case_examples_incll.test_case;
    Case_examples_kolm.test_case;
    Case_examples_lp.test_case;
    Case_examples_lp_horn.test_case;
    Case_examples_mini_ml.test_case;
    Case_examples_polylam.test_case;
    Case_examples_prop_calc.test_case;
    (*
    Case_examples_clp_arith.test_case;
    Case_examples_clp_base.test_case;
    Case_examples_clp_crypt.test_case;
    Case_examples_clp_integers.test_case;
    Case_examples_clp_laplace.test_case;
    Case_examples_clp_lists.test_case;
    Case_examples_clp_mortgage.test_case;
    Case_examples_clp_pelletier.test_case;
    Case_examples_clp_sieve.test_case;
    *)
    Case_examples_crary_explicit.test_case;
    Case_examples_crary_explicit_rev.test_case;
    Case_examples_crary_mldef_alpha.test_case;
    Case_examples_crary_mldef_alpha_sing.test_case;
    Case_examples_crary_standard.test_case;
    Case_examples_crary_substruct_linear.test_case;
    Case_examples_crary_substruct_lineard.test_case;
    Case_examples_crary_substruct_modal.test_case;
    Case_examples_crary_synsing.test_case;
    Case_examples_crary_tslf.test_case;
    Case_examples_crary_tslf_sing.test_case;
  ]
