; (include sources.dune)

(library
 (instrumentation
  (backend bisect_ppx))
 (name typecheck)
 (public_name stelf.typecheck)
 (modules Typecheck_ Strict STRICT TYPECHECK)
 (libraries display intsyn print paths names basis)
 (flags
  (:standard -w -A+5))
 (wrapped true)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
